import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblBack: String = "Back"
    static let kLblLogout: String = "Logout"
    static let kLblNext: String = "NEXT "
    static let kMsgMakeAFakeCal: String = "Make a fake call"
    static let kLblHome: String = "Home"
    static let kMsgAlreadyHaveAn: String = "Already have an account?  Sign in"
    static let kMsgYourPhoneNumb: String = "Your phone number (required)"
    static let kMsgEnterYourOpti: String = "Enter your Optional\nEmergency contacts:"
    static let kMsgEnterYourPass: String = "Enter your password*"
    static let kMsgYourLocationH: String =
        "Your location has been sent to 911 and your emergency contacts"
    static let kLblSignIn: String = "Sign in"
    static let kLblYourPassword: String = "Your password"
    static let kMsgThisWillTrigg: String =
        "This will trigger both “Send SMS” and\n“Get help nearby”."
    static let kLblReportAPerson: String = "Report a person"
    static let kMsgEnterEmergency12: String = "Enter Emergency Contact 3 Phone  *"
    static let kLblMap: String = "Map"
    static let kMsgEnterEmergency11: String = "Enter Emergency Contact 3 Name *"
    static let kMsgEnterEmergency10: String = "Enter Emergency Contact 2 Phone *"
    static let kLblAddAPhoto: String = "Add a photo."
    static let kLblHello: String = "Hello,\n"
    static let kMsgVictoriaRobert: String = "Victoria Robertson."
    static let kMsgEnterYourEme: String = "Enter your \nEmergency contacts:"
    static let kMsgWeProtectYou: String = "We protect you. Together."
    static let kMsgEnterEmergency: String = "Enter Emergency Contact 4 Name"
    static let kMsgYourNameRequ: String = "Your name (required)"
    static let kLblReportSent: String = "Report sent"
    static let kLblAngelShot: String = "Angel Shot"
    static let kMsgHelloVictoria: String = "Hello,\nVictoria Robertson."
    static let kMsgAlreadyHaveAn2: String = "Already have an account? "
    static let kMsgIsAskingForH: String = " is asking for help at "
    static let kMsgPleaseNoteTha2: String = "Please note that a profile picure is "
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgEnterYourEmer: String = "Enter your Emergency Contact 4:"
    static let kLblSignInWith: String = "Sign In with "
    static let kLblUser: String = "User"
    static let kLblAccept: String = "Accept"
    static let kMsgDontHaveAnAc2: String = "Dont have an account? "
    static let kLblRequired: String = "required"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgWalmartFletche: String = "Walmart Fletcher Ave. "
    static let kMsgViewEditProfi: String = "View/Edit profile"
    static let kLblYourEmail: String = "Your email"
    static let kMsgThisAllowsUs: String =
        "This allows us to locate your location to ensure your safety."
    static let kMsgPleaseAllowYo: String = "Please allow your location as Always."
    static let kMsgEnterYourPass2: String = "Enter your password *"
    static let kMsgUserSarahBull: String =
        "User Sarah Bullock is asking for help at Walmart Fletcher Ave. (1 mile away). Can you help them?"
    static let kMsgAlertPeopleTh: String = "Alert people that is closest to you to intervene."
    static let kMsgWeWillSendAn: String =
        "We will send an SMS of your location to 911 and your emergency contacts."
    static let kMsg1MileAway: String = "(1 mile away). Can you help them?"
    static let kMsgBrieflyDescrib: String = "Briefly describe the situation"
    static let kLblDecline: String = "Decline"
    static let kLblSmsSent: String = "SMS sent"
    static let kLblLogIn: String = "Log in."
    static let kMsgYourHelpMessa: String = "Your help message has been sent to nearby user(s)"
    static let kLblSOSMode: String = "S.O.S Mode"
    static let kLblHelpWanted: String = "Help Wanted"
    static let kMsgEnterEmergency8: String = "Enter Emergency Contact 1 Phone *"
    static let kLblMyReports: String = "My reports"
    static let kMsgEnterEmergency9: String = "Enter Emergency Contact 2 Name *"
    static let kMsgEnterEmergency4: String = "Enter Emergency Contact 5 Phone"
    static let kMsgEnterEmergency5: String = "Enter Emergency Contact 6 Name"
    static let kMsgEnterEmergency6: String = "Enter Emergency Contact 6 Phone"
    static let kLblSarahBullock: String = " Sarah Bullock"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblLogin2: String = "Login"
    static let kLblEnterYour: String = "Enter your "
    static let kMsgEnterEmergency7: String = "Enter Emergency Contact 1 Name *"
    static let kMsgReportToPolic: String = "Report to Police"
    static let kLblGetStarted: String = " Get Started"
    static let kMsgEnterEmergency2: String = "Enter Emergency Contact 4 Phone"
    static let kLblSignUp: String = "Sign up"
    static let kMsgEnterEmergency3: String = "Enter Emergency Contact 5 Name"
    static let kMsgAlreadyAMembe: String = "Already a member?"
    static let kMsgForPeopleToI: String = " for people to identify who you are."
    static let kMsgSendSmsOfYou: String =
        "Send SMS of your location to 911 and your emergency contacts."
    static let kMsgDontHaveAnAc: String = "Dont have an account?  Sign up"
    static let kMsgYourReportHas: String = "Your report has been sent to Police."
    static let kLblSkip: String = "Skip"
    static let kLblSendSms: String = "Send SMS"
    static let kLblProfile: String = "Profile"
    static let kMsgHowCanWeHelp: String = "How can we help you?"
    static let kMsgEnterYourEmai3: String = "Enter your email"
    static let kMsgVictoriaRobert2: String = "Victoria Robertson"
    static let kLblLogIn2: String = "Log in"
    static let kMsgEnterYourEmai2: String = "Enter your email *"
    static let kMsgDoYouWantTo: String = "Do you want to proceed?"
    static let kLbl00: String = "00"
    static let kLblHelpSent: String = "Help sent"
    static let kLblOptional: String = "Optional\n"
    static let kMsgDescriptionRe: String = "Description (Required)"
    static let kMsgEnterYourEmer5: String = "Enter your Emergency Contact 2:"
    static let kLblReturnToMenu: String = "Return to menu"
    static let kMsgEnterYourEmer4: String = "Enter your Emergency Contact 1:"
    static let kMsgEnterYourEmer6: String = "Enter your Emergency Contact 3:"
    static let kMsgEnterYourEmai: String = "Enter your email*"
    static let kMsgEmergencyConta: String = "Emergency contacts:"
    static let kMsgMyEmergencyCo: String = "My emergency contacts"
    static let kMsgEnterYourEmer3: String = "Enter your Emergency Contact 6:"
    static let kMsgPleaseNoteTha: String =
        "Please note that a profile picure is required for people to identify who you are."
    static let kMsgEnterYourEmer2: String = "Enter your Emergency Contact 5:"
    static let kMsgInitiateAFake: String = "Initiate a fake call to distract opponent."
    static let kLblSettings: String = "Settings"
    static let kLblHelp: String = "Help"
    static let kLblGetHelpNearby: String = "Get help nearby"
    static let kLblAlways: String = "Always."
    static let kMsgReportSuspicio: String =
        "Report suspicious and/or violating behavior to the police."
    static let kMsgEnterYourNum: String = "Enter your  number"
    static let kLblEnterYourName: String = "Enter your name"
    static let kMsgWeWillSendA: String = "We will send a help alert to users who is nearest to you."
    static let kMsgPleaseAllowYo2: String = "Please allow your location as "
}
